name: envato
description: A Project To Practice On Work In Team
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    # - family: Tajawal
    #   fonts:
    #     - asset: assets/fonts/Tajawal-Black.ttf
    #     - asset: assets/fonts/Tajawal-Bold.ttf
    #     - asset: assets/fonts/Tajawal-ExtraBold.ttf
    #     - asset: assets/fonts/Tajawal-ExtraLight.ttf
    #     - asset: assets/fonts/Tajawal-Light.ttf
    #     - asset: assets/fonts/Tajawal-Medium.ttf
    #     - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart